### ISSUE TITLE
regex exclusion on --containers not working

### ISSUE THREAD

**Issue by dwelch2344** [wercker/stern#21]
we have 2 containers in every pod, one always named `consul` which i want to filter. Would assume the following to work but no dice. Am I missing something? 

`stern --container "[^cC].*" "*"`

**Comment by akupila** [comment]
Hey @dwelch2344 

Sorry for the late response here. I think your problem is that the `.*` after the negated `c/C` still matches so basically it'll match any string. You could limit it so the text can't start with a `c` and things should work fine. Also the pod query needs `.*` (not just `*`), but that could be a copy-paste error.

Can you see if this works as expected:

```
stern --container "^[^cC].*" ".*"
```

**Comment by akupila** [comment]
Assuming you figured this out. Feel free to open a new issue if not
