### ISSUE TITLE
JSON logs

### ISSUE THREAD

**Issue by tmszdmsk** [wercker/stern#49]
Hi, we output our logs to `stdout` in JSON format. They're later captured by ELK stack. By using JSON we don't have to create log parsers. The drawback of this solution is that it's not super human readable when read not through Kibana. So my idea is to add some parameter that would allow you to display only specific fields from this JSON in a more human readable way. What do you think?

**Comment by hatchan** [comment]
I've added some support to be able to parse the output as JSON in https://github.com/wercker/stern/tree/json_support

The branch contains two changes:
- It will write logs to stdout, but not change events, those go to stderr.
- Using the `--no-prefix` flag it will remove the pod name from the logs, ie the raw content (maybe that should be the name of the flag :thinking: )

This allows you to pipe the result of stern to other applications, such as jq. Then you can do the filtering/projection/etc there.

Can you try that branch and let me know what you think?

**Comment by tmszdmsk** [comment]
Sounds great. I will check it tomorrow and let you know how it works ;)

**Comment by tmszdmsk** [comment]
I checked it, works like a charm!

**Comment by GJKrupa** [comment]
Just found this yesterday - it's a feature I was looking for since we also use LogStash format logs.  I've been using kubetail up to this point because of its --jq option but it has issues with leaving orphaned kubectl processes running after exit.  This works great other than one problem I've noticed (or maybe this isn't fully developed yet): the colour output doesn't seem to be working - it writes a colour key at the top of the output but the log lines themselves aren't coloured.

I'm running on Ubuntu 16.04 with Kubernetes 1.5.7 (client and server).

**Comment by hatchan** [comment]
I'll try to create a PR based on the `json_support` branch, with some slight tweaks a little bit later.

@GJKrupa 
> This works great other than one problem I've noticed (or maybe this isn't fully developed yet): the colour output doesn't seem to be working - it writes a colour key at the top of the output but the log lines themselves aren't coloured.

Do you mean with the `--no-prefix` flag? I was thinking of renaming that flag to raw which might make more sense, in that it won't add anything such as the prefix or colors.

**Comment by GJKrupa** [comment]
Exactly.  I've had a quick a play with jq and it looks like it tries to parse ANSI colour escape sequences as text, causing errors anyway so it's better to stick to plain text.  I'll have a look at doing what I'm trying (colour coding with jq parsing) through python/shell scripting instead since it's probably not a common use case.

**Comment by hatchan** [comment]
That's odd, if the `--no-prefix` flag is used, then it shouldn't add any colors: https://github.com/wercker/stern/compare/json_support#diff-032ac39618a8e9fa039ff30db880409aR159

**Comment by GJKrupa** [comment]
Sorry, I should clarify.  I was testing if jq could handle ANSI colours using _echo_ to send in small fragments of coloured JSON and it failed to parse them.

**Comment by gajus** [comment]
Any timeline until this is released to brew?

**Comment by xamox** [comment]
Any plans to get this merged in?

**Comment by hatchan** [comment]
Was working on a different approach which uses templates: https://github.com/wercker/stern/commit/19b52db58dea3ebc1b355edd45bf410548e4e540

So you can use the `-o raw` to get the raw output, which you can pipe to jq or something else. The template struct is not final and still need to work on documentation for this.

**Comment by xamox** [comment]
@hatchan Great, that method works for me as well.

**Comment by ostlerc** [comment]
What is holding this up?

**Comment by hatchan** [comment]
I've created a PR for this feature (you would use -o raw): https://github.com/wercker/stern/pull/76

**Comment by hatchan** [comment]
1.7.0 now supports templates, and by using the `-o raw` flag, you can pipe it in `jq` and change the shape in there: https://github.com/wercker/stern/releases/tag/1.7.0
