### ISSUE TITLE
Tail logs from initContainers

### ISSUE THREAD

**Issue by georgecrawford** [wercker/stern#53]
Hi,

Thanks for this great project! I couldn't find a way to tail logs from my initContainers. 

`stern 'api.*'` tails logs from all proper containers, but I see nothing from the initContainer
`kubectl logs api-2524184185-62d3c -c api-init` shows that I missed the logs from the init container named `api-ini`

It would be great if this could be added, as debugging initContainers is not so easy! Thanks.

**Comment by hatchan** [comment]
Hi, you should not use `api.*` but just `api`. And if you want to just filteron just 1 container within that pod, then you can just use `-c api-init`.

**Comment by georgecrawford** [comment]
OK, I'll try that. Thanks.

**Comment by russell** [comment]
I couldn't get this to work either.  It has no problem following main container.  But it seems to ignore init containers, even when I explicitly specify them like in your example.  I'm using k8s 1.7.5 and stern 1.5.1

**Comment by johnhamelink** [comment]
@russell I'm having the same issue with k8s 1.7.4 in prod, and with k8s 1.8 (minikube) in dev, and with stern 1.6.0.

**Comment by shun0309** [comment]
@hatchan Can I make a pull request to support pod.Status.InitContainerStatuses since it only loops through the main containers in https://github.com/wercker/stern/blob/master/stern/watch.go#L72, modified watch and deleted watch. Furthermore, can I also add a new command flag of container status which is by default "running" so that I can tail the containers in different statuses? Currently stern keeps waiting for containers in a loop. If the containers are not in running state, they are ignored silently and no error message is given. This could be quite confusing for users.
